// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Account struct {
	ID       string
	Name     string
	BudgetID string
	Closed   bool
	Balance  int64
	Cleared  int64
}

type Budget struct {
	ID   string
	Name string
}

type Job struct {
	ID        string
	Type      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Setting struct {
	Key   string
	Value string
}
