// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID       string
	Name     string
	BudgetID string
	Closed   bool
}

type Budget struct {
	ID   string
	Name string
}

type Job struct {
	Type           string
	Params         sql.NullString
	CronExpression string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Setting struct {
	Key   string
	Value string
}
