// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, name, budget_id, closed, balance, cleared) 
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAccountParams struct {
	ID       string
	Name     string
	BudgetID string
	Closed   bool
	Balance  int64
	Cleared  int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.BudgetID,
		arg.Closed,
		arg.Balance,
		arg.Cleared,
	)
	return err
}

const createBudget = `-- name: CreateBudget :exec
INSERT INTO budgets (id, name) VALUES (?, ?)
`

type CreateBudgetParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) error {
	_, err := q.db.ExecContext(ctx, createBudget, arg.ID, arg.Name)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, budget_id, closed, balance, cleared FROM accounts WHERE id = ? LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BudgetID,
		&i.Closed,
		&i.Balance,
		&i.Cleared,
	)
	return i, err
}

const getAccounts = `-- name: GetAccounts :many
SELECT id, name, budget_id, closed, balance, cleared FROM accounts
`

func (q *Queries) GetAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BudgetID,
			&i.Closed,
			&i.Balance,
			&i.Cleared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBudget = `-- name: GetBudget :one
SELECT id, name FROM budgets WHERE id = ? LIMIT 1
`

func (q *Queries) GetBudget(ctx context.Context, id string) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, id)
	var i Budget
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getBudgets = `-- name: GetBudgets :many
SELECT id, name FROM budgets
`

func (q *Queries) GetBudgets(ctx context.Context) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, getBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
