// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scheduler.sql

package database

import (
	"context"
	"database/sql"
)

const getJobs = `-- name: GetJobs :many
SELECT type
 ,cron_expression
 ,params
FROM jobs
`

type GetJobsRow struct {
	Type           string
	CronExpression string
	Params         sql.NullString
}

func (q *Queries) GetJobs(ctx context.Context) ([]GetJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobsRow
	for rows.Next() {
		var i GetJobsRow
		if err := rows.Scan(&i.Type, &i.CronExpression, &i.Params); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobCronExpression = `-- name: UpdateJobCronExpression :exec
UPDATE jobs 
SET cron_expression = ?
    ,updated_at = datetime('now')
WHERE type = ?
`

type UpdateJobCronExpressionParams struct {
	CronExpression string
	Type           string
}

func (q *Queries) UpdateJobCronExpression(ctx context.Context, arg UpdateJobCronExpressionParams) error {
	_, err := q.db.ExecContext(ctx, updateJobCronExpression, arg.CronExpression, arg.Type)
	return err
}
